### ISSUE TITLE
Definir requisitos funcionais do sistema

### ISSUE THREAD

**Issue by LuisinhoHN** [BeaCristina/GestaoViagens#6]
Definir principais funções da aplicação

**Comment by BeaCristina** [comment]
Descrição dos Processos do Sistema:

São 4 grupo de usuários: Viajantes, Gestores, Decisores Finais e Controladoria

- A viagem é iniciada por um Viajante ou um Gestor que deseja iniciar para um funcionário de sua gestão.
- Após Criada um pedido viagem ela é direcionada para o Gestor do viajante analisar o pedido de Viagem
- Após passar pelo gestor é checado se a viagem é nacional ou internacional
- Em uma viagem nacional se a viagem for em menos de 15 dias ela será encaminhada ao decisor final, se ela for internacional e em menos  de 30 dias também
- Caso não vá para um decisor final ela vai diretamente para a controladoria, se passar pelo decisor final vai pra controladoria também

**Comment by BeaCristina** [comment]
As viagens precisam sempre notificar por e-mail sempre que seus status/andamento alterar
